export const getEconomyMetrics = (comparison) => [
  {
    name: "Monthly Rent",
    cityOne: comparison.cityOne.rent,
    cityTwo: comparison.cityTwo.rent,
    winner: comparison.comparison.rent.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "currency",
    unit: "/mo",
    lowerIsBetter: true,
  },
  {
    name: "Food Cost",
    cityOne: comparison.cityOne.food,
    cityTwo: comparison.cityTwo.food,
    winner: comparison.comparison.food.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "index",
    unit: " pts",
    lowerIsBetter: true,
  },
  {
    name: "Transport",
    cityOne: comparison.cityOne.transport,
    cityTwo: comparison.cityTwo.transport,
    winner: comparison.comparison.transport.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "index",
    unit: " pts",
    lowerIsBetter: true,
  },
  {
    name: "Avg Salary",
    cityOne: comparison.cityOne.salary,
    cityTwo: comparison.cityTwo.salary,
    winner: comparison.comparison.salary.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "currency",
    unit: "/mo",
    lowerIsBetter: false,
  },
  {
    name: "Internet",
    cityOne: comparison.cityOne.internet,
    cityTwo: comparison.cityTwo.internet,
    winner: comparison.comparison.internet.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "currency",
    unit: "/mo",
    lowerIsBetter: true,
  },
];

export const getLifestyleMetrics = (comparison) => [
  {
    name: "Safety",
    cityOne: comparison.cityOne.safety,
    cityTwo: comparison.cityTwo.safety,
    winner: comparison.comparison.safety.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "index",
    unit: "/100",
    lowerIsBetter: false,
  },
  {
    name: "Healthcare",
    cityOne: comparison.cityOne.healthcare,
    cityTwo: comparison.cityTwo.healthcare,
    winner: comparison.comparison.healthcare.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "index",
    unit: "/100",
    lowerIsBetter: false,
  },
  {
    name: "Quality Of Life",
    cityOne: comparison.cityOne.qualityOfLife,
    cityTwo: comparison.cityTwo.qualityOfLife,
    winner: comparison.comparison.qualityOfLife.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "index",
    unit: " pts",
    lowerIsBetter: false,
  },
];

export const getEnvironmentMetrics = (comparison) => [
  {
    name: "Pollution",
    cityOne: comparison.cityOne.pollution,
    cityTwo: comparison.cityTwo.pollution,
    winner: comparison.comparison.pollution.winner,
    cityOneName: comparison.cityOne.city,
    cityTwoName: comparison.cityTwo.city,
    type: "index",
    unit: "/100",
    lowerIsBetter: true,
  },
];